### ISSUE TITLE
Data irregularities 2001 - 2002

### ISSUE THREAD

**Issue by semerj** [DataKind-SF/datadive_201503_techsoup-global#2]
I plotted the number of rows per day using the "date reg" variable. There's some missing data in 2001 and huge spikes in 2002. Maybe some of 2001 data was entered in 2002?

![date_reg_count](https://cloud.githubusercontent.com/assets/4423651/6757124/db2c7a5a-ceeb-11e4-9bc1-ea846c73170c.png)

**Comment by ericlwilliams** [comment]
Indeed, let's see what Steve has to say. Worst case scenario we go with > 2004/2005
